# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Starting CI/CD pipeline..."
    echo "Building Docker image..."
    docker build -f docker-webserver-task/Dockerfile -t docker-webserver:latest docker-webserver-task
  displayName: 'Build Docker Image'

- task: Docker@2
  displayName: 'Push Docker Image to ACR'
  inputs:
      command: 'buildAndPush'
      repository: 'docker-webserver'
      containerRegistry: 'acr-connection'
      tags: |
        latest

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'azurecicd-connection'
    appName: 'deesaxdockeracr'
    containers: 'deesaxdockeracr.azurecr.io/docker-webserver:latest'